name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      if: ${{ github.event_name == 'push' }}
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      if: ${{ github.event_name == 'push' }}
      uses: docker/setup-buildx-action@v2

    - name: login to docker hub
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v2
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build dockerfile with push
      if: ${{ github.event_name == 'push' }}
      # 构建镜像，用buildx可以同时构建X86和ARM架构的镜像，然后推送到hub.docker.com
      run: |
        fullCommit="${{ github.event.commits[0].id }}" && \
        docker buildx build \
        --output "type=image,push=true" \
        --file ./Dockerfile . \
        --tag rhysxia/outline:"${fullCommit: 0: 7}" \
        --tag rhysxia/outline:latest
      
